=== simeonhearring/app/core/src/test/resources/Components.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="Components" type="Components_Type"></xs:element>
	<xs:complexType name="Components_Type">
		<xs:all>
			<xs:element name="FieldTKG" type="FieldTKG_Type" minOccurs="0"></xs:element>
			<xs:element name="Heading" type="Heading_Type" minOccurs="0"></xs:element>
			<xs:element name="Badge" type="Badge_Type" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Some documentation</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="FieldSet" type="FieldSet_Type" minOccurs="0"></xs:element>
			<xs:element name="FormGroup" type="Collection_Type" minOccurs="0"></xs:element>
			<xs:element name="FormLabel" type="FormLabel_Type" minOccurs="0"></xs:element>
			<xs:element name="Icon" type="Icon_Type" minOccurs="0"></xs:element>
			<xs:element name="Input" type="Input_Type" minOccurs="0"></xs:element>
			<xs:element name="ListBox" type="ListBox_Type" minOccurs="0"></xs:element>
			<xs:element name="TextBox" type="TextBox_Type" minOccurs="0"></xs:element>
			<xs:element name="FlexTable" type="FlexTable_Type" minOccurs="0"></xs:element>
			<xs:element name="DatePicker" type="DatePicker_Type" minOccurs="0"></xs:element>
			<xs:element name="Typeahead" type="Typeahead_Type" minOccurs="0"></xs:element>
			<xs:element name="Button" type="Button_Type" minOccurs="0"></xs:element>
			<xs:element name="Panel" type="Panel_Type" minOccurs="0"></xs:element>
		</xs:all>
	</xs:complexType>
	<xs:complexType name="FieldTKG_Type">
		<xs:attribute name="fvt" type="xs:string" use="optional"></xs:attribute>
		<xs:attribute name="fvk" type="xs:string" use="optional"></xs:attribute>
		<xs:attribute name="fgg" type="xs:string" use="optional"></xs:attribute>
		<xs:attribute name="page.name" type="xs:string" use="optional"></xs:attribute>
	</xs:complexType>
	<xs:complexType name="ValueBoxBase_Type">
		<xs:sequence>
			<xs:element name="Placeholder" type="xs:string"></xs:element>
		</xs:sequence>
		<xs:attributeGroup ref="attr_ValueBoxBase"></xs:attributeGroup>
	</xs:complexType>
	<xs:complexType name="Button_Type">
		<xs:sequence>
			<xs:element name="Text" type="xs:string" minOccurs="0" maxOccurs="1"></xs:element>
			<xs:element name="Collection" type="Components_Type" minOccurs="0" maxOccurs="1"></xs:element>
		</xs:sequence>
		<xs:attributeGroup ref="attr_Button"></xs:attributeGroup>
	</xs:complexType>
	<xs:complexType name="Panel_Type">
		<xs:sequence>
			<xs:element name="PanelHeader" type="PanelHeader_Type" minOccurs="0" maxOccurs="1"></xs:element>
			<xs:element name="PanelBody" type="PanelBody_Type" minOccurs="0" maxOccurs="1"></xs:element>
			<xs:element name="PanelFooter" type="PanelFooter_Type" minOccurs="0" maxOccurs="1"></xs:element>
		</xs:sequence>
		<xs:attributeGroup ref="attr_Panel"></xs:attributeGroup>
	</xs:complexType>
	<xs:complexType name="PanelHeader_Type">
		<xs:sequence>
			<xs:any minOccurs="0"/>
		</xs:sequence>
		<xs:attributeGroup ref="attr_Panel"></xs:attributeGroup>
	</xs:complexType>
	<xs:complexType name="PanelBody_Type">
		<xs:sequence>
			<xs:any minOccurs="0"/>
		</xs:sequence>
		<xs:attributeGroup ref="attr_Panel"></xs:attributeGroup>
	</xs:complexType>
	<xs:complexType name="PanelFooter_Type">
		<xs:sequence>
			<xs:any minOccurs="0"/>
		</xs:sequence>
		<xs:attributeGroup ref="attr_Panel"></xs:attributeGroup>
	</xs:complexType>
	<xs:complexType name="Heading_Type">
		<xs:sequence>
			<xs:element name="Title" type="xs:string" minOccurs="0" maxOccurs="1"></xs:element>
			<xs:element name="Collection" type="Components_Type" minOccurs="0" maxOccurs="1"></xs:element>
			<xs:element name="Text" type="xs:string" minOccurs="0" maxOccurs="1"></xs:element>
			<xs:element name="SubText" type="xs:string" minOccurs="0" maxOccurs="1"></xs:element>
		</xs:sequence>
		<xs:attributeGroup ref="attr_Heading"></xs:attributeGroup>
	</xs:complexType>
	<xs:complexType name="FieldSet_Type">
		<xs:sequence>
			<xs:element name="Collection" type="FormGroup_Type" minOccurs="0"></xs:element>
		</xs:sequence>
		<xs:attribute name="enabled" type="xs:string"></xs:attribute>
		<xs:attributeGroup ref="attr_ComplexWidget"></xs:attributeGroup>
	</xs:complexType>
	<xs:complexType name="FormGroup_Type">
		<xs:sequence>
			<xs:element name="FormGroup" type="Collection_Type" minOccurs="0" maxOccurs="unbounded"></xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Collection_Type">
		<xs:all>
			<xs:element name="Collection" type="Components_Type"></xs:element>
		</xs:all>
	</xs:complexType>
	<xs:complexType name="Icon_Type">
		<xs:sequence>
			<xs:element name="Title" type="xs:string" minOccurs="0"></xs:element>
		</xs:sequence>
		<xs:attributeGroup ref="attr_Icon"></xs:attributeGroup>
	</xs:complexType>
	<xs:complexType name="FlexTable_Type">
		<xs:sequence>
			<xs:element name="Title" type="xs:string" minOccurs="0"></xs:element>
		</xs:sequence>
		<xs:attributeGroup ref="attr_UIObject"></xs:attributeGroup>
	</xs:complexType>
	<xs:complexType name="DatePicker_Type">
		<xs:sequence>
			<xs:element name="Title" type="xs:string" minOccurs="0"></xs:element>
		</xs:sequence>
		<xs:attributeGroup ref="attr_UIObject"></xs:attributeGroup>
	</xs:complexType>
	<xs:complexType name="Badge_Type">
		<xs:sequence>
			<xs:element name="Title" type="xs:string" minOccurs="0"></xs:element>
			<xs:element name="Text" type="xs:string"></xs:element>
		</xs:sequence>
		<xs:attributeGroup ref="attr_UIObject"></xs:attributeGroup>
	</xs:complexType>
	<xs:complexType name="Headers_Type">
		<xs:sequence>
			<xs:element name="string" type="xs:string" minOccurs="0" maxOccurs="unbounded"></xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Types_Type">
		<xs:sequence>
			<xs:element name="Type" type="xs:string" minOccurs="0" maxOccurs="unbounded"></xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="FormLabel_Type">
		<xs:sequence>
			<xs:element name="Text" type="xs:string" minOccurs="0" maxOccurs="1"></xs:element>
		</xs:sequence>
		<xs:attribute use="optional" name="showRequiredIndicator" type="xs:string"></xs:attribute>
		<xs:attributeGroup ref="attr_AbstractTextWidget"></xs:attributeGroup>
	</xs:complexType>
	<xs:complexType name="Input_Type" mixed="true">
		<xs:sequence>
			<xs:element minOccurs="0" name="Value" type="xs:string"></xs:element>
		</xs:sequence>
		<xs:attributeGroup ref="attr_Input"></xs:attributeGroup>
	</xs:complexType>
	<xs:complexType name="Typeahead_Type">
		<xs:sequence>
			<xs:element name="Value" type="xs:string" minOccurs="0"></xs:element>
			<xs:element name="Placeholder" type="xs:string" minOccurs="0"></xs:element>
			<xs:element name="Lookup" type="Lookup_Type"></xs:element>
		</xs:sequence>
		<xs:attributeGroup ref="attr_ValueBoxBase"></xs:attributeGroup>
	</xs:complexType>
	<xs:complexType name="TextBox_Type">
		<xs:sequence>
			<xs:element name="Value" type="xs:string" minOccurs="0"></xs:element>
		</xs:sequence>
		<xs:attributeGroup ref="attr_ValueBoxBase"></xs:attributeGroup>
	</xs:complexType>
	<xs:complexType name="ListBox_Type">
		<xs:sequence>
			<xs:element name="Lookup" type="Lookup_Type"></xs:element>
		</xs:sequence>
		<xs:attribute name="KEY" type="xs:string"></xs:attribute>
		<xs:attribute name="multipleSelect" type="xs:string"></xs:attribute>
	</xs:complexType>
	<xs:attributeGroup name="attr_UIObject">
		<xs:attribute name="KEY" type="xs:string" use="optional"></xs:attribute>
		<xs:attribute name="SECTION" type="xs:string" use="optional"></xs:attribute>
		<xs:attribute name="id" type="xs:string" use="optional"></xs:attribute>
		<xs:attribute name="visible" type="xs:string" use="optional"></xs:attribute>
		<xs:attribute name="height" type="xs:string" use="optional"></xs:attribute>
		<xs:attribute name="width" type="xs:string" use="optional"></xs:attribute>
		<xs:attribute name="style" type="xs:string" use="optional"></xs:attribute>
		<xs:attribute name="stylePrimary" type="xs:string" use="optional"></xs:attribute>
	</xs:attributeGroup>
	<xs:attributeGroup name="attr_ValueBoxBase">
		<xs:attribute name="allowBlank" type="xs:string" use="optional"></xs:attribute>
		<xs:attribute name="autoComplete" type="xs:string" use="optional"></xs:attribute>
		<xs:attribute name="maxLength" type="xs:string" use="optional"></xs:attribute>
		<xs:attribute name="size" type="xs:string" use="optional"></xs:attribute>
		<xs:attributeGroup ref="attr_UIObject"></xs:attributeGroup>
	</xs:attributeGroup>
	<xs:attributeGroup name="attr_Panel">
		<xs:attribute name="type" type="xs:string" use="required"></xs:attribute>
		<xs:attributeGroup ref="attr_UIObject"></xs:attributeGroup>
	</xs:attributeGroup>
	<xs:attributeGroup name="attr_Input">
		<xs:attribute name="type" type="xs:string" use="optional"></xs:attribute>
		<xs:attribute name="min" type="xs:string" use="optional"></xs:attribute>
		<xs:attribute name="max" type="xs:string" use="optional"></xs:attribute>
		<xs:attributeGroup ref="attr_UIObject"></xs:attributeGroup>
	</xs:attributeGroup>
	<xs:attributeGroup name="attr_AbstractTextWidget">
		<xs:attribute name="isHtml" type="xs:string" use="optional"></xs:attribute>
		<xs:attribute name="color" type="xs:string" use="optional"></xs:attribute>
		<xs:attribute name="marginLeft" type="xs:string" use="optional"></xs:attribute>
		<xs:attribute name="marginRight" type="xs:string" use="optional"></xs:attribute>
		<xs:attribute name="marginTop" type="xs:string" use="optional"></xs:attribute>
		<xs:attribute name="paddingBottom" type="xs:string" use="optional"></xs:attribute>
		<xs:attribute name="paddingLeft" type="xs:string" use="optional"></xs:attribute>
		<xs:attribute name="paddingRight" type="xs:string" use="optional"></xs:attribute>
		<xs:attribute name="paddingTop" type="xs:string" use="optional"></xs:attribute>
		<xs:attribute name="pull" type="xs:string" use="optional"></xs:attribute>
		<xs:attributeGroup ref="attr_UIObject"></xs:attributeGroup>
	</xs:attributeGroup>
	<xs:attributeGroup name="attr_Heading">
		<xs:attribute name="size" type="xs:string" use="optional"></xs:attribute>
		<xs:attribute name="emphasis" use="optional">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="DEFAULT"></xs:enumeration>
					<xs:enumeration value="MUTED"></xs:enumeration>
					<xs:enumeration value="PRIMARY"></xs:enumeration>
					<xs:enumeration value="SUCCESS"></xs:enumeration>
					<xs:enumeration value="INFO"></xs:enumeration>
					<xs:enumeration value="WARNING"></xs:enumeration>
					<xs:enumeration value="DANGER"></xs:enumeration>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="alignment" use="optional">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="DEFAULT"></xs:enumeration>
					<xs:enumeration value="LEFT"></xs:enumeration>
					<xs:enumeration value="CENTER"></xs:enumeration>
					<xs:enumeration value="RIGHT"></xs:enumeration>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attributeGroup ref="attr_ComplexWidget"></xs:attributeGroup>
	</xs:attributeGroup>
	<xs:attributeGroup name="attr_Button">
		<xs:attribute name="iconType" type="xs:string" use="optional"></xs:attribute>
		<xs:attribute name="toggleCaret" type="xs:string" use="optional"></xs:attribute>
		<xs:attribute name="dataToggle" type="xs:string" use="optional"></xs:attribute>
		<xs:attribute name="buttonType" use="optional">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="DEFAULT"></xs:enumeration>
					<xs:enumeration value="PRIMARY"></xs:enumeration>
					<xs:enumeration value="SUCCESS"></xs:enumeration>
					<xs:enumeration value="INFO"></xs:enumeration>
					<xs:enumeration value="WARNING"></xs:enumeration>
					<xs:enumeration value="DANGER"></xs:enumeration>
					<xs:enumeration value="LINK"></xs:enumeration>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="iconPosition" type="xs:string" use="optional"></xs:attribute>
		<xs:attribute name="iconFlip" type="xs:string" use="optional"></xs:attribute>
		<xs:attribute name="iconRotate" type="xs:string" use="optional"></xs:attribute>
		<xs:attribute name="iconBordered" type="xs:string" use="optional"></xs:attribute>
		<xs:attribute name="iconInverse" type="xs:string" use="optional"></xs:attribute>
		<xs:attribute name="iconSpin" type="xs:string" use="optional"></xs:attribute>
		<xs:attribute name="iconPulse" type="xs:string" use="optional"></xs:attribute>
		<xs:attribute name="iconFixedWidth" type="xs:string" use="optional"></xs:attribute>
		<xs:attribute name="badgeText" type="xs:string" use="optional"></xs:attribute>
		<xs:attribute name="badgePosition" type="xs:string" use="optional"></xs:attribute>
		<xs:attribute name="active" type="xs:string" use="optional"></xs:attribute>
		<xs:attribute name="enabled" type="xs:string" use="optional"></xs:attribute>
		<xs:attribute name="buttonSize" type="xs:string" use="optional"></xs:attribute>
		<xs:attribute name="iconSize" type="xs:string" use="optional"></xs:attribute>
		<xs:attributeGroup ref="attr_CommandName"></xs:attributeGroup>
		<xs:attributeGroup ref="attr_ComplexWidget"></xs:attributeGroup>
	</xs:attributeGroup>
	<xs:attributeGroup name="attr_Icon">
		<xs:attribute name="type" type="xs:string" use="optional"></xs:attribute>
		<xs:attribute name="size" type="xs:string" use="optional"></xs:attribute>
		<xs:attribute name="rotate" type="xs:string" use="optional"></xs:attribute>
		<xs:attribute name="flip" type="xs:string" use="optional"></xs:attribute>
		<xs:attribute name="emphasis" type="xs:string" use="optional"></xs:attribute>
		<xs:attribute name="border" type="xs:string" use="optional"></xs:attribute>
		<xs:attribute name="spin" type="xs:string" use="optional"></xs:attribute>
		<xs:attribute name="pulse" type="xs:string" use="optional"></xs:attribute>
		<xs:attribute name="inverse" type="xs:string" use="optional"></xs:attribute>
		<xs:attribute name="stackTop" type="xs:string" use="optional"></xs:attribute>
		<xs:attribute name="stackBase" type="xs:string" use="optional"></xs:attribute>
		<xs:attribute name="fixedWidth" type="xs:string" use="optional"></xs:attribute>
		<xs:attributeGroup ref="attr_ComplexWidget"></xs:attributeGroup>
	</xs:attributeGroup>
	<xs:attributeGroup name="attr_CommandName">
		<xs:attribute name="command.name" use="optional">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="LoginCommand"></xs:enumeration>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:attributeGroup>
	<xs:attributeGroup name="attr_ComplexWidget">
		<xs:attribute name="color" type="xs:string" use="optional"></xs:attribute>
		<xs:attribute name="marginBottom" type="xs:double" use="optional"></xs:attribute>
		<xs:attribute name="marginLeft" type="xs:double" use="optional"></xs:attribute>
		<xs:attribute name="marginRight" type="xs:double" use="optional"></xs:attribute>
		<xs:attribute name="marginTop" type="xs:double" use="optional"></xs:attribute>
		<xs:attribute name="paddingBottom" type="xs:double" use="optional"></xs:attribute>
		<xs:attribute name="paddingLeft" type="xs:double" use="optional"></xs:attribute>
		<xs:attribute name="paddingRight" type="xs:double" use="optional"></xs:attribute>
		<xs:attribute name="paddingTop" type="xs:double" use="optional"></xs:attribute>
		<xs:attribute name="pull" use="optional">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="NONE"></xs:enumeration>
					<xs:enumeration value="LEFT"></xs:enumeration>
					<xs:enumeration value="RIGHT"></xs:enumeration>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attributeGroup ref="attr_UIObject"></xs:attributeGroup>
	</xs:attributeGroup>
	<xs:group name="grp_UIObject">
		<xs:sequence>
			<xs:element name="Title" type="xs:string"></xs:element>
			<xs:element name="Placeholder" type="xs:string"></xs:element>
		</xs:sequence>
	</xs:group>
	<xs:complexType name="Lookup_Type">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="loc" use="required">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:enumeration value="TABLE"></xs:enumeration>
							<xs:enumeration value="RPC"></xs:enumeration>
						</xs:restriction>
					</xs:simpleType>
				</xs:attribute>
				<xs:attribute name="params" type="xs:string"></xs:attribute>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
</xs:schema>

=== simeonhearring/app/core/src/test/resources/Components1.xml
<?xml version="1.0" encoding="UTF-8"?>
<Components xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Components.xsd">
	<FieldTKG fvt="LOGIN" fgg="LOGIN" page.name="LOGIN" />
	<Heading SECTION="LOGINC01" size="H1" emphasis="INFO" alignment="LEFT">
		<Title>Login</Title>
		<Text>Login</Text>
	</Heading>
	<FieldSet SECTION="LOGINC01" enabled="true">
		<Collection>
			<FormGroup>
				<Collection>
					<FormLabel KEY="FL00_14" isHtml="false" />
					<Input KEY="FV00_14" type="TEXT" />
				</Collection>
			</FormGroup>
			<FormGroup>
				<Collection>
					<FormLabel KEY="FL00_15" isHtml="false" />
					<Input KEY="FV00_15" type="TEXT" />
				</Collection>
			</FormGroup>
			<FormGroup>
				<Collection>
					<Button KEY="BTN00_1" buttonType="SUCCESS" command.name="LoginCommand">
						<Text>Login</Text>
					</Button>
				</Collection>
			</FormGroup>
		</Collection>
	</FieldSet>
</Components>

=== simeonhearring/app/core/src/test/resources/Components2.xml
<?xml version="1.0" encoding="UTF-8"?>
<Components xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Components.xsd">
	<FieldTKG fvt="PERSON" fgg="JGRP1" page.layout="WEB" />
	<Heading SECTION="WEBC01" size="H1" emphasis="INFO" alignment="LEFT">
		<Title>Title</Title>
		<Text>Contact Information</Text>
		<SubText>Including address</SubText>
	</Heading>
	<Panel SECTION="WEBC01" type="DEFAULT">
		<Collection>
			<PanelHeader>
				<Collection>
					<Heading size="H5" emphasis="INFO" alignment="LEFT">
						<Text>Header Information</Text>
					</Heading>
				</Collection>
			</PanelHeader>
			<PanelBody>
				<Collection>
					<FieldSet enabled="true">
						<Collection>
							<Row>
								<Column size="SM_4">
									<Collection>
										<FormGroup>
											<Collection>
												<FormLabel KEY="FL00_1" isHtml="false" />
												<Input KEY="FV00_1" type="TEXT" />
											</Collection>
										</FormGroup>
									</Collection>
								</Column>
								<Column size="SM_4">
									<Collection>
										<FormGroup>
											<Collection>
												<FormLabel KEY="FL00_2" isHtml="false" />
												<Input KEY="FV00_2" type="TEXT" />
											</Collection>
										</FormGroup>
									</Collection>
								</Column>
								<Column size="SM_4">
									<Collection>
										<FormGroup>
											<Collection>
												<FormLabel KEY="FL00_3" isHtml="false" />
												<TextBox KEY="FV00_3" />
											</Collection>
										</FormGroup>
									</Collection>
								</Column>
							</Row>
							<FormGroup>
								<Collection>
									<FormLabel KEY="FL00_4" isHtml="false" />
									<DatePicker KEY="FV00_4" />
								</Collection>
							</FormGroup>
							<FormGroup>
								<Collection>
									<FormLabel KEY="FL00_16" isHtml="false" />
									<Typeahead KEY="FV00_16">
										<Lookup loc="RPC" params="BLANK,PROFILE" />
									</Typeahead>
								</Collection>
							</FormGroup>
							<FormGroup>
								<Collection>
									<FormLabel KEY="FL00_22" isHtml="false" />
									<Typeahead KEY="FV00_22">
										<Lookup loc="TABLE" params="BLANK,COMPONENTS" />
									</Typeahead>
								</Collection>
							</FormGroup>
							<FormGroup>
								<Collection>
									<FormLabel KEY="FL00_12" isHtml="false" />
									<ListBox KEY="FV00_12" multipleSelect="false">
										<Lookup loc="TABLE" params="BLANK,GENDER,UNKNOWN" />
									</ListBox>
								</Collection>
							</FormGroup>
						</Collection>
					</FieldSet>
				</Collection>
			</PanelBody>
			<PanelFooter>
				<Collection>
					<Heading color="red" size="H5" emphasis="INFO" alignment="LEFT">
						<Text>Footer</Text>
					</Heading>
				</Collection>
			</PanelFooter>
		</Collection>
	</Panel>
	<Panel SECTION="WEBC01" type="DEFAULT">
		<Collection>
			<PanelHeader>
				<Collection>
					<Heading color="red" size="H5" emphasis="INFO" alignment="LEFT">
						<Text>Address Information</Text>
					</Heading>
				</Collection>
			</PanelHeader>
			<PanelBody>
				<Collection>
					<FieldSet enabled="true">
						<Collection>
							<FormGroup>
								<Collection>
									<FormLabel KEY="FL00_13" isHtml="false">
										<Text>address:</Text>
									</FormLabel>
									<FlexTable KEY="FV00_13" width="100%">
										<Title>Title</Title>
									</FlexTable>
								</Collection>
							</FormGroup>
						</Collection>
					</FieldSet>
				</Collection>
			</PanelBody>
			<PanelFooter>
				<Collection>
					<Heading color="red" size="H5" emphasis="INFO" alignment="LEFT">
						<Text>Footer</Text>
					</Heading>
				</Collection>
			</PanelFooter>
		</Collection>
	</Panel>
	<Icon SECTION="WEBL01" pull="LEFT" type="AMAZON" size="LARGE" border="true" spin="false" pulse="false" inverse="false">
		<Title>Title</Title>
	</Icon>
	<Badge SECTION="WEBR01">
		<Title>Title</Title>
		<Text>Text</Text>
	</Badge>
</Components>

=== simeonhearring/app/core/src/main/resources/Page1.xml
<?xml version="1.0" encoding="UTF-8"?>
<Components xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Components.xsd">
	<TableKey table="JUNIT" group="JGRP2" />
	<Heading SECTION="LOGINC01" size="H1" emphasis="INFO" alignment="LEFT">
		<Title>Login</Title>
		<Text>Login</Text>
	</Heading>
	<FieldSet SECTION="LOGINC01" enabled="true">
		<Collection>
			<FormGroup>
				<Collection>
					<FormLabel KEY="FL00_14" isHtml="false" />
					<Input KEY="FV00_14" type="TEXT" />
				</Collection>
			</FormGroup>
			<FormGroup>
				<Collection>
					<FormLabel KEY="FL00_15" isHtml="false" />
					<Input KEY="FV00_15" type="TEXT" />
				</Collection>
			</FormGroup>
			<FormGroup>
				<Collection>
					<Button KEY="BT00_2" buttonType="SUCCESS">
						<Text>Login</Text>
					</Button>
				</Collection>
			</FormGroup>
		</Collection>
	</FieldSet>
</Components>

=== simeonhearring/app/core/src/main/resources/Components2.xml
<?xml version="1.0" encoding="UTF-8"?>
<Components xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Components.xsd">
	<FieldTKG fvt="JUNIT" fgg="JGRP1" page.name="WEB" />
	<Heading SECTION="WEBC01" color="red" size="H1" emphasis="INFO" alignment="LEFT">
		<Title>Title</Title>
		<Text>Contact Information</Text>
		<SubText>Including address</SubText>
	</Heading>
	<FieldSet SECTION="WEBC01" enabled="true">
		<Collection>
			<FormGroup>
				<Collection>
					<FormLabel KEY="FL00_1" isHtml="false" />
					<Input KEY="FV00_1" type="TEXT" />
				</Collection>
			</FormGroup>
			<FormGroup>
				<Collection>
					<FormLabel KEY="FL00_2" isHtml="false" />
					<Input KEY="FV00_2" type="TEXT" />
				</Collection>
			</FormGroup>
			<FormGroup>
				<Collection>
					<FormLabel KEY="FL00_3" isHtml="false" />
					<TextBox KEY="FV00_3" />
				</Collection>
			</FormGroup>
			<FormGroup>
				<Collection>
					<FormLabel KEY="FL00_12" isHtml="false" />
					<ListBox KEY="FV00_12" multipleSelect="false">
						<Lookup loc="TABLE" params="BLANK,GENDER,UNKNOWN" />
					</ListBox>
				</Collection>
			</FormGroup>
			<FormGroup>
				<Collection>
					<FormLabel KEY="FL00_13" isHtml="false">
						<Text>Field4:</Text>
					</FormLabel>
					<FlexTable KEY="FV00_13">
						<Title>Title</Title>
					</FlexTable>
				</Collection>
			</FormGroup>
		</Collection>
	</FieldSet>
	<Icon SECTION="WEBL01" pull="LEFT" type="AMAZON" size="LARGE" border="true" spin="false" pulse="false" inverse="false">
		<Title>Title</Title>
	</Icon>
	<Badge SECTION="WEBR01">
		<Title>Title</Title>
		<Text>Text</Text>
	</Badge>
</Components>

=== simeonhearring/app/core/src/test/resources/cLAND.xml
<?xml version="1.0" encoding="UTF-8"?>
<Components xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Components.xsd">
	<FieldTKG fvt="PERSON" fgg="PERSON" page.layout="WEB" />
	<Heading SECTION="CENTER_01" size="H1" emphasis="INFO" alignment="LEFT">
		<Title>Title</Title>
		<Text>Contact Information</Text>
		<SubText>Including address</SubText>
	</Heading>
	<Panel SECTION="CENTER_01" type="DEFAULT">
		<Collection>
			<PanelHeader>
				<Collection>
					<Heading size="H5" emphasis="INFO" alignment="LEFT">
						<Text>Header Information</Text>
					</Heading>
				</Collection>
			</PanelHeader>
			<PanelBody>
				<Collection>
					<FieldSet enabled="true">
						<Collection>
							<Row>
								<Column size="SM_4">
									<Collection>
										<FormGroup>
											<Collection>
												<FormLabel KEY="FL00_-4" isHtml="false">
													<Text>first:</Text>
												</FormLabel>
												<Input KEY="FV00_-4" type="TEXT" />
											</Collection>
										</FormGroup>
									</Collection>
								</Column>
								<Column size="SM_4">
									<Collection>
										<FormGroup>
											<Collection>
												<FormLabel KEY="FL00_-6" isHtml="false">
													<Text>middle:</Text>
												</FormLabel>
												<TextBox KEY="FV00_-6" />
											</Collection>
										</FormGroup>
									</Collection>
								</Column>
								<Column size="SM_4">
									<Collection>
										<FormGroup>
											<Collection>
												<FormLabel KEY="FL00_-5" isHtml="false">
													<Text>last:</Text>
												</FormLabel>
												<Input KEY="FV00_-5" type="TEXT" />
											</Collection>
										</FormGroup>
									</Collection>
								</Column>
							</Row>
							<FormGroup>
								<Collection>
									<FormLabel KEY="FL00_-12" isHtml="false">
										<Text>dob:</Text>
									</FormLabel>
									<DatePicker KEY="FV00_-12" />
								</Collection>
							</FormGroup>
							<FormGroup>
								<Collection>
									<FormLabel KEY="FL00_-11" isHtml="false">
										<Text>profile:</Text>
									</FormLabel>
									<Typeahead KEY="FV00_-11">
										<Lookup loc="RPC" params="BLANK,PROFILE" />
									</Typeahead>
								</Collection>
							</FormGroup>
							<FormGroup>
								<Collection>
									<FormLabel KEY="FL00_-8" isHtml="false">
										<Text>page:</Text>
									</FormLabel>
									<Typeahead KEY="FV00_-8">
										<Lookup loc="TABLE" params="BLANK,COMPONENTS" />
									</Typeahead>
								</Collection>
							</FormGroup>
							<FormGroup>
								<Collection>
									<FormLabel KEY="FL00_-7" isHtml="false">
										<Text>gender:</Text>
									</FormLabel>
									<ListBox KEY="FV00_-7" multipleSelect="false">
										<Lookup loc="TABLE" params="BLANK,GENDER,UNKNOWN" />
									</ListBox>
								</Collection>
							</FormGroup>
						</Collection>
					</FieldSet>
				</Collection>
			</PanelBody>
			<PanelFooter>
				<Collection>
					<Heading color="red" size="H5" emphasis="INFO" alignment="LEFT">
						<Text>Footer</Text>
					</Heading>
				</Collection>
			</PanelFooter>
		</Collection>
	</Panel>
	<Icon SECTION="LEFT_01" pull="LEFT" type="AMAZON" size="LARGE" border="true" spin="false" pulse="false" inverse="false">
		<Title>Title</Title>
	</Icon>
	<Badge SECTION="RIGHT_01">
		<Title>Title</Title>
		<Text>Text</Text>
	</Badge>
</Components>
